# Dockerfile

# Playwright destekli resmi imaj
FROM mcr.microsoft.com/playwright/python:v1.54.0-jammy

# Çalışma dizini
WORKDIR /app

# Gerekli dosyaları kopyala
COPY requirements.txt .
COPY . .

# Pip ile kurulum ve Chromium yükle
RUN pip install --no-cache-dir -r requirements.txt
RUN playwright install chromium

# API'yi başlat
CMD ["python", "api.py"]
